-- RentStage v0.9 — tenant-branded public catalogs and anonymous quote requests.

CREATE TABLE public_catalog_settings (
  tenant_id UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  headline TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  cover_image_url TEXT,
  accent_color TEXT NOT NULL DEFAULT '#6657F7',
  show_prices BOOLEAN NOT NULL DEFAULT TRUE,
  show_resources BOOLEAN NOT NULL DEFAULT TRUE,
  quote_requests_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  contact_email TEXT,
  contact_phone TEXT,
  contact_address TEXT,
  terms_text TEXT NOT NULL DEFAULT 'Al enviar esta solicitud autorizas al proveedor a contactarte para preparar una cotización. La disponibilidad mostrada es una referencia y no constituye una reserva.',
  terms_version TEXT NOT NULL DEFAULT '1.0',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT public_catalog_headline_length CHECK (CHAR_LENGTH(headline) <= 180),
  CONSTRAINT public_catalog_description_length CHECK (CHAR_LENGTH(description) <= 4000),
  CONSTRAINT public_catalog_cover_url_length CHECK (cover_image_url IS NULL OR CHAR_LENGTH(cover_image_url) <= 2000),
  CONSTRAINT public_catalog_accent_color_format CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  CONSTRAINT public_catalog_contact_email_length CHECK (contact_email IS NULL OR CHAR_LENGTH(contact_email) <= 320),
  CONSTRAINT public_catalog_contact_phone_length CHECK (contact_phone IS NULL OR CHAR_LENGTH(contact_phone) <= 40),
  CONSTRAINT public_catalog_contact_address_length CHECK (contact_address IS NULL OR CHAR_LENGTH(contact_address) <= 500),
  CONSTRAINT public_catalog_terms_length CHECK (CHAR_LENGTH(terms_text) BETWEEN 1 AND 4000),
  CONSTRAINT public_catalog_terms_version_length CHECK (CHAR_LENGTH(terms_version) BETWEEN 1 AND 40)
);

ALTER TABLE packages
  ADD COLUMN public_visible BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN public_featured BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN public_sort_order INTEGER NOT NULL DEFAULT 0;

ALTER TABLE packages
  ADD CONSTRAINT packages_public_sort_order_nonnegative CHECK (public_sort_order >= 0),
  ADD CONSTRAINT packages_public_featured_requires_visible CHECK (NOT public_featured OR public_visible),
  ADD CONSTRAINT packages_public_visible_requires_active CHECK (NOT public_visible OR active);

ALTER TABLE resources
  ADD COLUMN public_slug TEXT,
  ADD COLUMN public_description TEXT NOT NULL DEFAULT '',
  ADD COLUMN public_image_url TEXT,
  ADD COLUMN public_visible BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN public_featured BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN public_sort_order INTEGER NOT NULL DEFAULT 0;

ALTER TABLE resources
  ADD CONSTRAINT resources_public_slug_format CHECK (public_slug IS NULL OR public_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  ADD CONSTRAINT resources_public_slug_length CHECK (public_slug IS NULL OR CHAR_LENGTH(public_slug) <= 140),
  ADD CONSTRAINT resources_public_description_length CHECK (CHAR_LENGTH(public_description) <= 4000),
  ADD CONSTRAINT resources_public_image_url_length CHECK (public_image_url IS NULL OR CHAR_LENGTH(public_image_url) <= 2000),
  ADD CONSTRAINT resources_public_sort_order_nonnegative CHECK (public_sort_order >= 0),
  ADD CONSTRAINT resources_public_featured_requires_visible CHECK (NOT public_featured OR public_visible),
  ADD CONSTRAINT resources_public_visible_requires_active CHECK (NOT public_visible OR active),
  ADD CONSTRAINT resources_public_visible_requires_slug CHECK (NOT public_visible OR public_slug IS NOT NULL);

CREATE UNIQUE INDEX idx_resources_tenant_public_slug
  ON resources(tenant_id, public_slug)
  WHERE public_slug IS NOT NULL;

CREATE INDEX idx_packages_public_catalog
  ON packages(tenant_id, public_visible, public_featured DESC, public_sort_order, name)
  WHERE active = TRUE;

CREATE INDEX idx_resources_public_catalog
  ON resources(tenant_id, public_visible, public_featured DESC, public_sort_order, name)
  WHERE active = TRUE;

CREATE TABLE quote_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  request_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reference_code TEXT NOT NULL DEFAULT ('RQ-' || UPPER(SUBSTRING(ENCODE(gen_random_bytes(8), 'hex') FROM 1 FOR 12))),
  status TEXT NOT NULL DEFAULT 'NEW'
    CHECK (status IN ('NEW', 'IN_REVIEW', 'CONVERTED', 'CLOSED', 'SPAM')),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL DEFAULT '',
  phone TEXT,
  email TEXT,
  company_name TEXT,
  preferred_language TEXT NOT NULL DEFAULT 'es' CHECK (preferred_language IN ('es', 'en')),
  event_type TEXT,
  event_location TEXT,
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  estimated_subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  estimated_discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  estimated_extra_charges NUMERIC(12,2) NOT NULL DEFAULT 0,
  estimated_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL,
  availability_available BOOLEAN NOT NULL DEFAULT FALSE,
  availability_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  terms_text TEXT NOT NULL,
  terms_version TEXT NOT NULL,
  consent_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  submitter_hash TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  converted_customer_id UUID,
  converted_quote_id UUID,
  handled_at TIMESTAMPTZ,
  handled_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, request_number),
  UNIQUE (reference_code),
  CONSTRAINT quote_requests_reference_format CHECK (reference_code ~ '^RQ-[A-F0-9]{12}$'),
  CONSTRAINT quote_requests_period_valid CHECK (end_at > start_at),
  CONSTRAINT quote_requests_first_name_not_blank CHECK (BTRIM(first_name) <> ''),
  CONSTRAINT quote_requests_first_name_length CHECK (CHAR_LENGTH(first_name) <= 120),
  CONSTRAINT quote_requests_last_name_length CHECK (CHAR_LENGTH(last_name) <= 120),
  CONSTRAINT quote_requests_email_length CHECK (email IS NULL OR CHAR_LENGTH(email) <= 320),
  CONSTRAINT quote_requests_phone_length CHECK (phone IS NULL OR CHAR_LENGTH(phone) <= 40),
  CONSTRAINT quote_requests_company_length CHECK (company_name IS NULL OR CHAR_LENGTH(company_name) <= 180),
  CONSTRAINT quote_requests_event_type_length CHECK (event_type IS NULL OR CHAR_LENGTH(event_type) <= 120),
  CONSTRAINT quote_requests_location_length CHECK (event_location IS NULL OR CHAR_LENGTH(event_location) <= 500),
  CONSTRAINT quote_requests_notes_length CHECK (CHAR_LENGTH(notes) <= 6000),
  CONSTRAINT quote_requests_terms_text_length CHECK (CHAR_LENGTH(terms_text) BETWEEN 1 AND 4000),
  CONSTRAINT quote_requests_terms_version_length CHECK (CHAR_LENGTH(terms_version) BETWEEN 1 AND 40),
  CONSTRAINT quote_requests_user_agent_length CHECK (CHAR_LENGTH(user_agent) <= 500),
  CONSTRAINT quote_requests_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT quote_requests_contact_present CHECK (email IS NOT NULL OR phone IS NOT NULL),
  CONSTRAINT quote_requests_consent_required CHECK (consent_accepted),
  CONSTRAINT quote_requests_subtotal_nonnegative CHECK (estimated_subtotal >= 0),
  CONSTRAINT quote_requests_discount_nonnegative CHECK (estimated_discount_amount >= 0),
  CONSTRAINT quote_requests_discount_within_subtotal CHECK (estimated_discount_amount <= estimated_subtotal),
  CONSTRAINT quote_requests_extra_charges_nonnegative CHECK (estimated_extra_charges >= 0),
  CONSTRAINT quote_requests_total_nonnegative CHECK (estimated_total >= 0),
  CONSTRAINT quote_requests_total_consistent CHECK (
    estimated_total = estimated_subtotal - estimated_discount_amount + estimated_extra_charges
  ),
  CONSTRAINT quote_requests_conversion_consistent CHECK (
    (status <> 'CONVERTED' AND converted_quote_id IS NULL AND converted_customer_id IS NULL)
    OR
    (status = 'CONVERTED' AND converted_quote_id IS NOT NULL AND converted_customer_id IS NOT NULL)
  ),
  FOREIGN KEY (tenant_id, converted_customer_id)
    REFERENCES customers(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, converted_quote_id)
    REFERENCES quotes(tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE quote_request_packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  quote_request_id UUID NOT NULL,
  package_id UUID,
  package_name TEXT NOT NULL,
  package_slug TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0 AND quantity <= 100),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),
  template JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, quote_request_id, package_slug),
  CONSTRAINT quote_request_packages_name_length CHECK (CHAR_LENGTH(package_name) <= 180),
  CONSTRAINT quote_request_packages_slug_format CHECK (package_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  CONSTRAINT quote_request_packages_slug_length CHECK (CHAR_LENGTH(package_slug) <= 140),
  FOREIGN KEY (tenant_id, quote_request_id)
    REFERENCES quote_requests(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, package_id)
    REFERENCES packages(tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE quote_request_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  quote_request_id UUID NOT NULL,
  resource_id UUID NOT NULL,
  resource_name TEXT NOT NULL,
  description TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0 AND quantity <= 10000),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, quote_request_id, resource_id),
  CONSTRAINT quote_request_items_name_length CHECK (CHAR_LENGTH(resource_name) <= 180),
  CONSTRAINT quote_request_items_description_length CHECK (CHAR_LENGTH(description) <= 500),
  CONSTRAINT quote_request_items_discount_valid CHECK (discount_amount <= quantity * unit_price),
  CONSTRAINT quote_request_items_total_consistent CHECK (line_total = quantity * unit_price - discount_amount),
  FOREIGN KEY (tenant_id, quote_request_id)
    REFERENCES quote_requests(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, resource_id)
    REFERENCES resources(tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_quote_requests_tenant_status_created
  ON quote_requests(tenant_id, status, created_at DESC);

CREATE INDEX idx_quote_requests_tenant_submitter_created
  ON quote_requests(tenant_id, submitter_hash, created_at DESC)
  WHERE submitter_hash <> '';

CREATE INDEX idx_quote_request_packages_request
  ON quote_request_packages(tenant_id, quote_request_id, sort_order, id);

CREATE INDEX idx_quote_request_items_request
  ON quote_request_items(tenant_id, quote_request_id, sort_order, id);

DROP TRIGGER IF EXISTS public_catalog_settings_set_updated_at ON public_catalog_settings;
CREATE TRIGGER public_catalog_settings_set_updated_at
BEFORE UPDATE ON public_catalog_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS quote_requests_set_updated_at ON quote_requests;
CREATE TRIGGER quote_requests_set_updated_at
BEFORE UPDATE ON quote_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
